# Generated by Django 6.0.1 on 2026-01-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
